spring.application.name=api-gateway
server.port=4004

# Required by JwtValidationGatewayFilterFactory
auth.service.url=http://localhost:4005

# Patient Service
spring.cloud.gateway.routes[0].id=patient-service
spring.cloud.gateway.routes[0].uri=http://localhost:4000
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/patients/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[0].filters[1]=JwtValidation

# Billing Service
spring.cloud.gateway.routes[1].id=billing-service
spring.cloud.gateway.routes[1].uri=http://localhost:4001
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/billing/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[1].filters[1]=JwtValidation

# Auth Service 
spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=http://localhost:4005
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=2



# H2 Console 
spring.cloud.gateway.routes[3].id=patient-h2-console
spring.cloud.gateway.routes[3].uri=http://localhost:4000
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/h2-console/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=2